variables:
  PLUGIN_NAME: 'authorsHistory'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs_plugins_unit_tests_model.yml'